# Generated by Django 2.2.7 on 2019-11-20 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_habit', '0002_article_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Habit',
        ),
    ]
